// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.

import {
  ethereum,
  JSONValue,
  TypedMap,
  Entity,
  Bytes,
  Address,
  BigInt
} from "@graphprotocol/graph-ts";

export class GuardianChanged extends ethereum.Event {
  get params(): GuardianChanged__Params {
    return new GuardianChanged__Params(this);
  }
}

export class GuardianChanged__Params {
  _event: GuardianChanged;

  constructor(event: GuardianChanged) {
    this._event = event;
  }

  get oldGuardian(): Address {
    return this._event.parameters[0].value.toAddress();
  }

  get newGuardian(): Address {
    return this._event.parameters[1].value.toAddress();
  }
}

export class NodeWithdrawalAddressSet extends ethereum.Event {
  get params(): NodeWithdrawalAddressSet__Params {
    return new NodeWithdrawalAddressSet__Params(this);
  }
}

export class NodeWithdrawalAddressSet__Params {
  _event: NodeWithdrawalAddressSet;

  constructor(event: NodeWithdrawalAddressSet) {
    this._event = event;
  }

  get node(): Address {
    return this._event.parameters[0].value.toAddress();
  }

  get withdrawalAddress(): Address {
    return this._event.parameters[1].value.toAddress();
  }

  get time(): BigInt {
    return this._event.parameters[2].value.toBigInt();
  }
}

export class rocketStorage extends ethereum.SmartContract {
  static bind(address: Address): rocketStorage {
    return new rocketStorage("rocketStorage", address);
  }

  getAddress(_key: Bytes): Address {
    let result = super.call("getAddress", "getAddress(bytes32):(address)", [
      ethereum.Value.fromFixedBytes(_key)
    ]);

    return result[0].toAddress();
  }

  try_getAddress(_key: Bytes): ethereum.CallResult<Address> {
    let result = super.tryCall("getAddress", "getAddress(bytes32):(address)", [
      ethereum.Value.fromFixedBytes(_key)
    ]);
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toAddress());
  }

  getBool(_key: Bytes): boolean {
    let result = super.call("getBool", "getBool(bytes32):(bool)", [
      ethereum.Value.fromFixedBytes(_key)
    ]);

    return result[0].toBoolean();
  }

  try_getBool(_key: Bytes): ethereum.CallResult<boolean> {
    let result = super.tryCall("getBool", "getBool(bytes32):(bool)", [
      ethereum.Value.fromFixedBytes(_key)
    ]);
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toBoolean());
  }

  getBytes(_key: Bytes): Bytes {
    let result = super.call("getBytes", "getBytes(bytes32):(bytes)", [
      ethereum.Value.fromFixedBytes(_key)
    ]);

    return result[0].toBytes();
  }

  try_getBytes(_key: Bytes): ethereum.CallResult<Bytes> {
    let result = super.tryCall("getBytes", "getBytes(bytes32):(bytes)", [
      ethereum.Value.fromFixedBytes(_key)
    ]);
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toBytes());
  }

  getBytes32(_key: Bytes): Bytes {
    let result = super.call("getBytes32", "getBytes32(bytes32):(bytes32)", [
      ethereum.Value.fromFixedBytes(_key)
    ]);

    return result[0].toBytes();
  }

  try_getBytes32(_key: Bytes): ethereum.CallResult<Bytes> {
    let result = super.tryCall("getBytes32", "getBytes32(bytes32):(bytes32)", [
      ethereum.Value.fromFixedBytes(_key)
    ]);
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toBytes());
  }

  getDeployedStatus(): boolean {
    let result = super.call(
      "getDeployedStatus",
      "getDeployedStatus():(bool)",
      []
    );

    return result[0].toBoolean();
  }

  try_getDeployedStatus(): ethereum.CallResult<boolean> {
    let result = super.tryCall(
      "getDeployedStatus",
      "getDeployedStatus():(bool)",
      []
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toBoolean());
  }

  getGuardian(): Address {
    let result = super.call("getGuardian", "getGuardian():(address)", []);

    return result[0].toAddress();
  }

  try_getGuardian(): ethereum.CallResult<Address> {
    let result = super.tryCall("getGuardian", "getGuardian():(address)", []);
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toAddress());
  }

  getInt(_key: Bytes): BigInt {
    let result = super.call("getInt", "getInt(bytes32):(int256)", [
      ethereum.Value.fromFixedBytes(_key)
    ]);

    return result[0].toBigInt();
  }

  try_getInt(_key: Bytes): ethereum.CallResult<BigInt> {
    let result = super.tryCall("getInt", "getInt(bytes32):(int256)", [
      ethereum.Value.fromFixedBytes(_key)
    ]);
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toBigInt());
  }

  getNodePendingWithdrawalAddress(_nodeAddress: Address): Address {
    let result = super.call(
      "getNodePendingWithdrawalAddress",
      "getNodePendingWithdrawalAddress(address):(address)",
      [ethereum.Value.fromAddress(_nodeAddress)]
    );

    return result[0].toAddress();
  }

  try_getNodePendingWithdrawalAddress(
    _nodeAddress: Address
  ): ethereum.CallResult<Address> {
    let result = super.tryCall(
      "getNodePendingWithdrawalAddress",
      "getNodePendingWithdrawalAddress(address):(address)",
      [ethereum.Value.fromAddress(_nodeAddress)]
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toAddress());
  }

  getNodeWithdrawalAddress(_nodeAddress: Address): Address {
    let result = super.call(
      "getNodeWithdrawalAddress",
      "getNodeWithdrawalAddress(address):(address)",
      [ethereum.Value.fromAddress(_nodeAddress)]
    );

    return result[0].toAddress();
  }

  try_getNodeWithdrawalAddress(
    _nodeAddress: Address
  ): ethereum.CallResult<Address> {
    let result = super.tryCall(
      "getNodeWithdrawalAddress",
      "getNodeWithdrawalAddress(address):(address)",
      [ethereum.Value.fromAddress(_nodeAddress)]
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toAddress());
  }

  getString(_key: Bytes): string {
    let result = super.call("getString", "getString(bytes32):(string)", [
      ethereum.Value.fromFixedBytes(_key)
    ]);

    return result[0].toString();
  }

  try_getString(_key: Bytes): ethereum.CallResult<string> {
    let result = super.tryCall("getString", "getString(bytes32):(string)", [
      ethereum.Value.fromFixedBytes(_key)
    ]);
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toString());
  }

  getUint(_key: Bytes): BigInt {
    let result = super.call("getUint", "getUint(bytes32):(uint256)", [
      ethereum.Value.fromFixedBytes(_key)
    ]);

    return result[0].toBigInt();
  }

  try_getUint(_key: Bytes): ethereum.CallResult<BigInt> {
    let result = super.tryCall("getUint", "getUint(bytes32):(uint256)", [
      ethereum.Value.fromFixedBytes(_key)
    ]);
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toBigInt());
  }
}

export class ConstructorCall extends ethereum.Call {
  get inputs(): ConstructorCall__Inputs {
    return new ConstructorCall__Inputs(this);
  }

  get outputs(): ConstructorCall__Outputs {
    return new ConstructorCall__Outputs(this);
  }
}

export class ConstructorCall__Inputs {
  _call: ConstructorCall;

  constructor(call: ConstructorCall) {
    this._call = call;
  }
}

export class ConstructorCall__Outputs {
  _call: ConstructorCall;

  constructor(call: ConstructorCall) {
    this._call = call;
  }
}

export class AddUintCall extends ethereum.Call {
  get inputs(): AddUintCall__Inputs {
    return new AddUintCall__Inputs(this);
  }

  get outputs(): AddUintCall__Outputs {
    return new AddUintCall__Outputs(this);
  }
}

export class AddUintCall__Inputs {
  _call: AddUintCall;

  constructor(call: AddUintCall) {
    this._call = call;
  }

  get _key(): Bytes {
    return this._call.inputValues[0].value.toBytes();
  }

  get _amount(): BigInt {
    return this._call.inputValues[1].value.toBigInt();
  }
}

export class AddUintCall__Outputs {
  _call: AddUintCall;

  constructor(call: AddUintCall) {
    this._call = call;
  }
}

export class ConfirmGuardianCall extends ethereum.Call {
  get inputs(): ConfirmGuardianCall__Inputs {
    return new ConfirmGuardianCall__Inputs(this);
  }

  get outputs(): ConfirmGuardianCall__Outputs {
    return new ConfirmGuardianCall__Outputs(this);
  }
}

export class ConfirmGuardianCall__Inputs {
  _call: ConfirmGuardianCall;

  constructor(call: ConfirmGuardianCall) {
    this._call = call;
  }
}

export class ConfirmGuardianCall__Outputs {
  _call: ConfirmGuardianCall;

  constructor(call: ConfirmGuardianCall) {
    this._call = call;
  }
}

export class ConfirmWithdrawalAddressCall extends ethereum.Call {
  get inputs(): ConfirmWithdrawalAddressCall__Inputs {
    return new ConfirmWithdrawalAddressCall__Inputs(this);
  }

  get outputs(): ConfirmWithdrawalAddressCall__Outputs {
    return new ConfirmWithdrawalAddressCall__Outputs(this);
  }
}

export class ConfirmWithdrawalAddressCall__Inputs {
  _call: ConfirmWithdrawalAddressCall;

  constructor(call: ConfirmWithdrawalAddressCall) {
    this._call = call;
  }

  get _nodeAddress(): Address {
    return this._call.inputValues[0].value.toAddress();
  }
}

export class ConfirmWithdrawalAddressCall__Outputs {
  _call: ConfirmWithdrawalAddressCall;

  constructor(call: ConfirmWithdrawalAddressCall) {
    this._call = call;
  }
}

export class DeleteAddressCall extends ethereum.Call {
  get inputs(): DeleteAddressCall__Inputs {
    return new DeleteAddressCall__Inputs(this);
  }

  get outputs(): DeleteAddressCall__Outputs {
    return new DeleteAddressCall__Outputs(this);
  }
}

export class DeleteAddressCall__Inputs {
  _call: DeleteAddressCall;

  constructor(call: DeleteAddressCall) {
    this._call = call;
  }

  get _key(): Bytes {
    return this._call.inputValues[0].value.toBytes();
  }
}

export class DeleteAddressCall__Outputs {
  _call: DeleteAddressCall;

  constructor(call: DeleteAddressCall) {
    this._call = call;
  }
}

export class DeleteBoolCall extends ethereum.Call {
  get inputs(): DeleteBoolCall__Inputs {
    return new DeleteBoolCall__Inputs(this);
  }

  get outputs(): DeleteBoolCall__Outputs {
    return new DeleteBoolCall__Outputs(this);
  }
}

export class DeleteBoolCall__Inputs {
  _call: DeleteBoolCall;

  constructor(call: DeleteBoolCall) {
    this._call = call;
  }

  get _key(): Bytes {
    return this._call.inputValues[0].value.toBytes();
  }
}

export class DeleteBoolCall__Outputs {
  _call: DeleteBoolCall;

  constructor(call: DeleteBoolCall) {
    this._call = call;
  }
}

export class DeleteBytesCall extends ethereum.Call {
  get inputs(): DeleteBytesCall__Inputs {
    return new DeleteBytesCall__Inputs(this);
  }

  get outputs(): DeleteBytesCall__Outputs {
    return new DeleteBytesCall__Outputs(this);
  }
}

export class DeleteBytesCall__Inputs {
  _call: DeleteBytesCall;

  constructor(call: DeleteBytesCall) {
    this._call = call;
  }

  get _key(): Bytes {
    return this._call.inputValues[0].value.toBytes();
  }
}

export class DeleteBytesCall__Outputs {
  _call: DeleteBytesCall;

  constructor(call: DeleteBytesCall) {
    this._call = call;
  }
}

export class DeleteBytes32Call extends ethereum.Call {
  get inputs(): DeleteBytes32Call__Inputs {
    return new DeleteBytes32Call__Inputs(this);
  }

  get outputs(): DeleteBytes32Call__Outputs {
    return new DeleteBytes32Call__Outputs(this);
  }
}

export class DeleteBytes32Call__Inputs {
  _call: DeleteBytes32Call;

  constructor(call: DeleteBytes32Call) {
    this._call = call;
  }

  get _key(): Bytes {
    return this._call.inputValues[0].value.toBytes();
  }
}

export class DeleteBytes32Call__Outputs {
  _call: DeleteBytes32Call;

  constructor(call: DeleteBytes32Call) {
    this._call = call;
  }
}

export class DeleteIntCall extends ethereum.Call {
  get inputs(): DeleteIntCall__Inputs {
    return new DeleteIntCall__Inputs(this);
  }

  get outputs(): DeleteIntCall__Outputs {
    return new DeleteIntCall__Outputs(this);
  }
}

export class DeleteIntCall__Inputs {
  _call: DeleteIntCall;

  constructor(call: DeleteIntCall) {
    this._call = call;
  }

  get _key(): Bytes {
    return this._call.inputValues[0].value.toBytes();
  }
}

export class DeleteIntCall__Outputs {
  _call: DeleteIntCall;

  constructor(call: DeleteIntCall) {
    this._call = call;
  }
}

export class DeleteStringCall extends ethereum.Call {
  get inputs(): DeleteStringCall__Inputs {
    return new DeleteStringCall__Inputs(this);
  }

  get outputs(): DeleteStringCall__Outputs {
    return new DeleteStringCall__Outputs(this);
  }
}

export class DeleteStringCall__Inputs {
  _call: DeleteStringCall;

  constructor(call: DeleteStringCall) {
    this._call = call;
  }

  get _key(): Bytes {
    return this._call.inputValues[0].value.toBytes();
  }
}

export class DeleteStringCall__Outputs {
  _call: DeleteStringCall;

  constructor(call: DeleteStringCall) {
    this._call = call;
  }
}

export class DeleteUintCall extends ethereum.Call {
  get inputs(): DeleteUintCall__Inputs {
    return new DeleteUintCall__Inputs(this);
  }

  get outputs(): DeleteUintCall__Outputs {
    return new DeleteUintCall__Outputs(this);
  }
}

export class DeleteUintCall__Inputs {
  _call: DeleteUintCall;

  constructor(call: DeleteUintCall) {
    this._call = call;
  }

  get _key(): Bytes {
    return this._call.inputValues[0].value.toBytes();
  }
}

export class DeleteUintCall__Outputs {
  _call: DeleteUintCall;

  constructor(call: DeleteUintCall) {
    this._call = call;
  }
}

export class SetAddressCall extends ethereum.Call {
  get inputs(): SetAddressCall__Inputs {
    return new SetAddressCall__Inputs(this);
  }

  get outputs(): SetAddressCall__Outputs {
    return new SetAddressCall__Outputs(this);
  }
}

export class SetAddressCall__Inputs {
  _call: SetAddressCall;

  constructor(call: SetAddressCall) {
    this._call = call;
  }

  get _key(): Bytes {
    return this._call.inputValues[0].value.toBytes();
  }

  get _value(): Address {
    return this._call.inputValues[1].value.toAddress();
  }
}

export class SetAddressCall__Outputs {
  _call: SetAddressCall;

  constructor(call: SetAddressCall) {
    this._call = call;
  }
}

export class SetBoolCall extends ethereum.Call {
  get inputs(): SetBoolCall__Inputs {
    return new SetBoolCall__Inputs(this);
  }

  get outputs(): SetBoolCall__Outputs {
    return new SetBoolCall__Outputs(this);
  }
}

export class SetBoolCall__Inputs {
  _call: SetBoolCall;

  constructor(call: SetBoolCall) {
    this._call = call;
  }

  get _key(): Bytes {
    return this._call.inputValues[0].value.toBytes();
  }

  get _value(): boolean {
    return this._call.inputValues[1].value.toBoolean();
  }
}

export class SetBoolCall__Outputs {
  _call: SetBoolCall;

  constructor(call: SetBoolCall) {
    this._call = call;
  }
}

export class SetBytesCall extends ethereum.Call {
  get inputs(): SetBytesCall__Inputs {
    return new SetBytesCall__Inputs(this);
  }

  get outputs(): SetBytesCall__Outputs {
    return new SetBytesCall__Outputs(this);
  }
}

export class SetBytesCall__Inputs {
  _call: SetBytesCall;

  constructor(call: SetBytesCall) {
    this._call = call;
  }

  get _key(): Bytes {
    return this._call.inputValues[0].value.toBytes();
  }

  get _value(): Bytes {
    return this._call.inputValues[1].value.toBytes();
  }
}

export class SetBytesCall__Outputs {
  _call: SetBytesCall;

  constructor(call: SetBytesCall) {
    this._call = call;
  }
}

export class SetBytes32Call extends ethereum.Call {
  get inputs(): SetBytes32Call__Inputs {
    return new SetBytes32Call__Inputs(this);
  }

  get outputs(): SetBytes32Call__Outputs {
    return new SetBytes32Call__Outputs(this);
  }
}

export class SetBytes32Call__Inputs {
  _call: SetBytes32Call;

  constructor(call: SetBytes32Call) {
    this._call = call;
  }

  get _key(): Bytes {
    return this._call.inputValues[0].value.toBytes();
  }

  get _value(): Bytes {
    return this._call.inputValues[1].value.toBytes();
  }
}

export class SetBytes32Call__Outputs {
  _call: SetBytes32Call;

  constructor(call: SetBytes32Call) {
    this._call = call;
  }
}

export class SetDeployedStatusCall extends ethereum.Call {
  get inputs(): SetDeployedStatusCall__Inputs {
    return new SetDeployedStatusCall__Inputs(this);
  }

  get outputs(): SetDeployedStatusCall__Outputs {
    return new SetDeployedStatusCall__Outputs(this);
  }
}

export class SetDeployedStatusCall__Inputs {
  _call: SetDeployedStatusCall;

  constructor(call: SetDeployedStatusCall) {
    this._call = call;
  }
}

export class SetDeployedStatusCall__Outputs {
  _call: SetDeployedStatusCall;

  constructor(call: SetDeployedStatusCall) {
    this._call = call;
  }
}

export class SetGuardianCall extends ethereum.Call {
  get inputs(): SetGuardianCall__Inputs {
    return new SetGuardianCall__Inputs(this);
  }

  get outputs(): SetGuardianCall__Outputs {
    return new SetGuardianCall__Outputs(this);
  }
}

export class SetGuardianCall__Inputs {
  _call: SetGuardianCall;

  constructor(call: SetGuardianCall) {
    this._call = call;
  }

  get _newAddress(): Address {
    return this._call.inputValues[0].value.toAddress();
  }
}

export class SetGuardianCall__Outputs {
  _call: SetGuardianCall;

  constructor(call: SetGuardianCall) {
    this._call = call;
  }
}

export class SetIntCall extends ethereum.Call {
  get inputs(): SetIntCall__Inputs {
    return new SetIntCall__Inputs(this);
  }

  get outputs(): SetIntCall__Outputs {
    return new SetIntCall__Outputs(this);
  }
}

export class SetIntCall__Inputs {
  _call: SetIntCall;

  constructor(call: SetIntCall) {
    this._call = call;
  }

  get _key(): Bytes {
    return this._call.inputValues[0].value.toBytes();
  }

  get _value(): BigInt {
    return this._call.inputValues[1].value.toBigInt();
  }
}

export class SetIntCall__Outputs {
  _call: SetIntCall;

  constructor(call: SetIntCall) {
    this._call = call;
  }
}

export class SetStringCall extends ethereum.Call {
  get inputs(): SetStringCall__Inputs {
    return new SetStringCall__Inputs(this);
  }

  get outputs(): SetStringCall__Outputs {
    return new SetStringCall__Outputs(this);
  }
}

export class SetStringCall__Inputs {
  _call: SetStringCall;

  constructor(call: SetStringCall) {
    this._call = call;
  }

  get _key(): Bytes {
    return this._call.inputValues[0].value.toBytes();
  }

  get _value(): string {
    return this._call.inputValues[1].value.toString();
  }
}

export class SetStringCall__Outputs {
  _call: SetStringCall;

  constructor(call: SetStringCall) {
    this._call = call;
  }
}

export class SetUintCall extends ethereum.Call {
  get inputs(): SetUintCall__Inputs {
    return new SetUintCall__Inputs(this);
  }

  get outputs(): SetUintCall__Outputs {
    return new SetUintCall__Outputs(this);
  }
}

export class SetUintCall__Inputs {
  _call: SetUintCall;

  constructor(call: SetUintCall) {
    this._call = call;
  }

  get _key(): Bytes {
    return this._call.inputValues[0].value.toBytes();
  }

  get _value(): BigInt {
    return this._call.inputValues[1].value.toBigInt();
  }
}

export class SetUintCall__Outputs {
  _call: SetUintCall;

  constructor(call: SetUintCall) {
    this._call = call;
  }
}

export class SetWithdrawalAddressCall extends ethereum.Call {
  get inputs(): SetWithdrawalAddressCall__Inputs {
    return new SetWithdrawalAddressCall__Inputs(this);
  }

  get outputs(): SetWithdrawalAddressCall__Outputs {
    return new SetWithdrawalAddressCall__Outputs(this);
  }
}

export class SetWithdrawalAddressCall__Inputs {
  _call: SetWithdrawalAddressCall;

  constructor(call: SetWithdrawalAddressCall) {
    this._call = call;
  }

  get _nodeAddress(): Address {
    return this._call.inputValues[0].value.toAddress();
  }

  get _newWithdrawalAddress(): Address {
    return this._call.inputValues[1].value.toAddress();
  }

  get _confirm(): boolean {
    return this._call.inputValues[2].value.toBoolean();
  }
}

export class SetWithdrawalAddressCall__Outputs {
  _call: SetWithdrawalAddressCall;

  constructor(call: SetWithdrawalAddressCall) {
    this._call = call;
  }
}

export class SubUintCall extends ethereum.Call {
  get inputs(): SubUintCall__Inputs {
    return new SubUintCall__Inputs(this);
  }

  get outputs(): SubUintCall__Outputs {
    return new SubUintCall__Outputs(this);
  }
}

export class SubUintCall__Inputs {
  _call: SubUintCall;

  constructor(call: SubUintCall) {
    this._call = call;
  }

  get _key(): Bytes {
    return this._call.inputValues[0].value.toBytes();
  }

  get _amount(): BigInt {
    return this._call.inputValues[1].value.toBigInt();
  }
}

export class SubUintCall__Outputs {
  _call: SubUintCall;

  constructor(call: SubUintCall) {
    this._call = call;
  }
}
